Use `js_sys` for timestamps on wasm
The `time::offset_date_time::OffsetDateTime::now_utc` method is not supported
on wasm so tests are failing, e.g.:

```
---- zxcvbn::tests::test_zxcvbn output ----
    JS exception that was thrown:
        RuntimeError: unreachable
            at std::panicking::rust_panic_with_hook::h12b2f0179ff84c92 (wasm-function[1153]:0x10c7c0)
            at std::panicking::begin_panic_handler::{{closure}}::h5a69bb4aef967681 (wasm-function[1382]:0x116ce3)
            at std::sys_common::backtrace::__rust_end_short_backtrace::h1cfd7c1c16d2a171 (wasm-function[2088]:0x124723)
            at rust_begin_unwind (wasm-function[1814]:0x121c81)
            at core::panicking::panic_fmt::hf0d93ec1ac504cf9 (wasm-function[1892]:0x122c8b)
            at std::time::SystemTime::now::h49de6187ac1d5e3a (wasm-function[1819]:0x121dad)
            at time::offset_date_time::OffsetDateTime::now_utc::h2d66247c2dbb80d7 (wasm-function[1946]:0x1235c7)
            at zxcvbn::zxcvbn::hfa813456b60e2c30 (wasm-function[273]:0xaa086)
            at zxcvbn::tests::test_zxcvbn::ha19f0600170d3116 (wasm-function[588]:0xde745)
            at <wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::hf9360eaa0c633af0 (wasm-function[1732]:0x1204ac)
```

Instead use `js_sys::Date` when building for wasm.

Previously, before 9d3fee9a63ee ("Port from chrono to time 0.3"), `js_sys` was used
indirectly via `chrono`, now it is explicit.